import java.awt.image.BufferedImage;
import sistemaTomografico.SistemaTomografico;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LAURA
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfazGrafica
     */
    Imagen imagen;
    PreProcesamientoImagen imagenPreProcesada;    
    BufferedImage imagenOriginal;
    BufferedImage imagenOriginalCopia;
    
    int anchoImagenOriginal;
    int altoImagenOriginal;
    int tipoImagenOriginal;
    
    public InterfazGrafica() {
        this.initComponents(); // this...
        this.imagen = null;
        this.imagenPreProcesada = null;
        this.imagenOriginal = null;
        this.imagenOriginalCopia = null;
        this.anchoImagenOriginal = 0;
        this.altoImagenOriginal = 0;
        this.tipoImagenOriginal = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenOriginalLabel = new javax.swing.JLabel();
        imagenGrisLabel = new javax.swing.JLabel();
        imagenFiltradaLabel = new javax.swing.JLabel();
        imagenOriginalResultadoLabel = new javax.swing.JLabel();
        imagenResultadoFinalLabel = new javax.swing.JLabel();
        imagenCaracteristicasLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        imagenOriginalButton = new javax.swing.JButton();
        imagenGrisButton = new javax.swing.JButton();
        intensidadPixelButton = new javax.swing.JButton();
        binarizarButton = new javax.swing.JButton();
        imagenOriginalResultadoButton = new javax.swing.JButton();
        imagenResultadoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contornoButton = new javax.swing.JButton();
        entrenarButton = new javax.swing.JButton();
        histograma = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        preProcesarBoton = new javax.swing.JButton();
        CaracteristicasButton = new javax.swing.JButton();
        caracteristicas = new javax.swing.JLabel();
        normalizarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        imagenOriginalLabel.setBackground(new java.awt.Color(102, 204, 255));
        imagenOriginalLabel.setForeground(new java.awt.Color(204, 204, 255));
        imagenOriginalLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        imagenGrisLabel.setBackground(new java.awt.Color(102, 204, 255));
        imagenGrisLabel.setForeground(new java.awt.Color(204, 204, 255));
        imagenGrisLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        imagenFiltradaLabel.setBackground(new java.awt.Color(102, 204, 255));
        imagenFiltradaLabel.setForeground(new java.awt.Color(204, 204, 255));
        imagenFiltradaLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        imagenOriginalResultadoLabel.setBackground(new java.awt.Color(51, 204, 255));
        imagenOriginalResultadoLabel.setForeground(new java.awt.Color(51, 204, 255));
        imagenOriginalResultadoLabel.setText("jLabel4");
        imagenOriginalResultadoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));

        imagenResultadoFinalLabel.setForeground(new java.awt.Color(0, 204, 255));
        imagenResultadoFinalLabel.setText("jLabel5");
        imagenResultadoFinalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));

        imagenCaracteristicasLabel.setBackground(new java.awt.Color(102, 204, 255));
        imagenCaracteristicasLabel.setForeground(new java.awt.Color(204, 204, 255));
        imagenCaracteristicasLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 255));

        imagenOriginalButton.setText("Contorno 1");
        imagenOriginalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenOriginalButtonActionPerformed(evt);
            }
        });

        imagenGrisButton.setText("Escala de Grises");
        imagenGrisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenGrisButtonActionPerformed(evt);
            }
        });

        intensidadPixelButton.setText("Intensidad Pixel");
        intensidadPixelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intensidadPixelButtonActionPerformed(evt);
            }
        });

        binarizarButton.setText("Binarización");
        binarizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binarizarButtonActionPerformed(evt);
            }
        });

        imagenOriginalResultadoButton.setText("Agregar Imagen");
        imagenOriginalResultadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenOriginalResultadoButtonActionPerformed(evt);
            }
        });

        imagenResultadoButton.setText("Imagen Analizada");
        imagenResultadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagenResultadoButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("SISTEMA DE DETECCIÓN DE TUMORES CEREBRALES BASADO EN EL ANÁLISIS DE IMÁGENES TOMOGRÁFICAS");

        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("FASES DE ANÁLISIS DE LAS IMÁGENES TOMOGRÁFICAS");

        contornoButton.setText("Contorno 2");
        contornoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contornoButtonActionPerformed(evt);
            }
        });

        entrenarButton.setText("Entrenar");
        entrenarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrenarButtonActionPerformed(evt);
            }
        });

        histograma.setBackground(new java.awt.Color(102, 204, 255));
        histograma.setForeground(new java.awt.Color(204, 204, 255));
        histograma.setToolTipText("");
        histograma.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        jButton1.setText("Histograma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        preProcesarBoton.setText("Preprocesar");
        preProcesarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preProcesarBotonActionPerformed(evt);
            }
        });

        CaracteristicasButton.setText("Caracteisticas");
        CaracteristicasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaracteristicasButtonActionPerformed(evt);
            }
        });

        caracteristicas.setBackground(new java.awt.Color(102, 204, 255));
        caracteristicas.setForeground(new java.awt.Color(204, 204, 255));
        caracteristicas.setToolTipText("");
        caracteristicas.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 255)));

        normalizarButton.setText("Normalizar");
        normalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(imagenGrisButton)
                        .addGap(91, 91, 91)
                        .addComponent(intensidadPixelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagenGrisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(imagenFiltradaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(contornoButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagenOriginalButton)
                                .addGap(128, 128, 128)
                                .addComponent(binarizarButton)
                                .addGap(120, 120, 120)
                                .addComponent(jButton1)
                                .addGap(124, 124, 124)
                                .addComponent(CaracteristicasButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(imagenOriginalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(imagenCaracteristicasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(histograma, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(caracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imagenOriginalResultadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(imagenOriginalResultadoButton)))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imagenResultadoFinalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(preProcesarBoton)
                                            .addComponent(normalizarButton)
                                            .addComponent(entrenarButton))
                                        .addGap(111, 111, 111))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(imagenResultadoButton)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jLabel1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(normalizarButton)
                                .addGap(27, 27, 27)
                                .addComponent(entrenarButton)
                                .addGap(33, 33, 33)
                                .addComponent(preProcesarBoton)
                                .addGap(60, 60, 60))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imagenOriginalResultadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagenResultadoFinalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(imagenOriginalResultadoButton)
                                    .addComponent(imagenResultadoButton))
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imagenFiltradaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(imagenGrisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(imagenCaracteristicasLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(histograma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caracteristicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(imagenOriginalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(binarizarButton)
                            .addComponent(jButton1)
                            .addComponent(CaracteristicasButton)
                            .addComponent(imagenOriginalButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intensidadPixelButton)
                            .addComponent(imagenGrisButton))))
                .addGap(18, 18, 18)
                .addComponent(contornoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        imagenGrisLabel.getAccessibleContext().setAccessibleName("jLabel2");
        imagenFiltradaLabel.getAccessibleContext().setAccessibleName("jLabel3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagenOriginalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenOriginalButtonActionPerformed
        //imagen = new Imagen();            
        //imagen.visualizarImagen(imagenOriginalLabel);
        imagenPreProcesada.visualizarImagenContorno(imagenOriginalLabel);
    }//GEN-LAST:event_imagenOriginalButtonActionPerformed

    private void imagenResultadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenResultadoButtonActionPerformed
        imagenPreProcesada.visualizarRespuesta(imagenResultadoFinalLabel);
    }//GEN-LAST:event_imagenResultadoButtonActionPerformed

    private void intensidadPixelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intensidadPixelButtonActionPerformed
       // imagenPreProcesada = new PreProcesamientoImagen();
        imagenPreProcesada.visualizarFiltradoImagen(imagenFiltradaLabel);
    }//GEN-LAST:event_intensidadPixelButtonActionPerformed

    private void imagenOriginalResultadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenOriginalResultadoButtonActionPerformed
        imagen = new Imagen(); 
        imagenOriginal = imagen.agregarImagen(imagenOriginalResultadoLabel);
    }//GEN-LAST:event_imagenOriginalResultadoButtonActionPerformed

    private void imagenGrisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagenGrisButtonActionPerformed
        imagenPreProcesada = new PreProcesamientoImagen();
        imagenOriginalCopia = imagenOriginal;
        imagenPreProcesada.visualizarImagenEscalaGris(imagenOriginalCopia, imagenGrisLabel);
    }//GEN-LAST:event_imagenGrisButtonActionPerformed

    private void binarizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binarizarButtonActionPerformed
        imagenPreProcesada.visualizarImagenBinarizada(imagenCaracteristicasLabel);
    }//GEN-LAST:event_binarizarButtonActionPerformed

    private void contornoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contornoButtonActionPerformed
        imagenPreProcesada.visualizarImagenContorno2(imagenOriginalLabel);
    }//GEN-LAST:event_contornoButtonActionPerformed

    private void entrenarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrenarButtonActionPerformed
        imagen = new Imagen();            
        imagen.procesarImagenes();
    }//GEN-LAST:event_entrenarButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imagenPreProcesada.verHistograma(histograma);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void preProcesarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preProcesarBotonActionPerformed
        imagenPreProcesada = new PreProcesamientoImagen();
        imagenOriginalCopia = imagenOriginal;
        imagenPreProcesada.visualizarImagenEscalaGris(imagenOriginalCopia, imagenGrisLabel);
        imagenPreProcesada.visualizarFiltradoImagen(imagenFiltradaLabel);
        imagenPreProcesada.visualizarImagenContorno(imagenOriginalLabel);        
        imagenPreProcesada.visualizarImagenContorno2(imagenOriginalLabel);
        imagenPreProcesada.verHistograma(histograma);
        imagenPreProcesada.visualizarImagenBinarizada(imagenCaracteristicasLabel);
    }//GEN-LAST:event_preProcesarBotonActionPerformed

    private void CaracteristicasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaracteristicasButtonActionPerformed
        imagenPreProcesada.visualizarCaracteristicas(caracteristicas);
    }//GEN-LAST:event_CaracteristicasButtonActionPerformed

    private void normalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalizarButtonActionPerformed
        NormalizarImagenes n = new NormalizarImagenes();
        n.normalizar();
    }//GEN-LAST:event_normalizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaracteristicasButton;
    private javax.swing.JButton binarizarButton;
    private javax.swing.JLabel caracteristicas;
    private javax.swing.JButton contornoButton;
    private javax.swing.JButton entrenarButton;
    private javax.swing.JLabel histograma;
    private javax.swing.JLabel imagenCaracteristicasLabel;
    private javax.swing.JLabel imagenFiltradaLabel;
    private javax.swing.JButton imagenGrisButton;
    private javax.swing.JLabel imagenGrisLabel;
    private javax.swing.JButton imagenOriginalButton;
    private javax.swing.JLabel imagenOriginalLabel;
    private javax.swing.JButton imagenOriginalResultadoButton;
    private javax.swing.JLabel imagenOriginalResultadoLabel;
    private javax.swing.JButton imagenResultadoButton;
    private javax.swing.JLabel imagenResultadoFinalLabel;
    private javax.swing.JButton intensidadPixelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton normalizarButton;
    private javax.swing.JButton preProcesarBoton;
    // End of variables declaration//GEN-END:variables
}
